#include "draw.h"
#include "gba.h"
#include "images/title.h"
#include "images/dirt.h"
#include "images/shovel.h"
#include "images/stone.h"
#include "images/diamond.h"
#include "images/end.h"

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
// #include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

// This function will be used to draw everything about the app
// including the background and whatnot.
void drawCells(Cell cells[]) {
    for (int i = 0; i < 25; i++) {
        if (cells[i].dug == 0) {
            drawImageDMA(85 + (i % 5) * CELLSIZE, 5 + i / 5 * CELLSIZE, CELLSIZE, CELLSIZE, diamond);
        } else {
            drawImageDMA(85 + (i % 5) * CELLSIZE, 5 + i / 5 * CELLSIZE, CELLSIZE, CELLSIZE, stone);
        }
    }
}

void fullDrawAppState(AppState *state) {
    drawFullScreenImageDMA(dirt);
    drawCells(state->cells);
    drawImageDMA(state->cursor.x, state->cursor.y, 20, 20, shovel);
    char *progression = "Diamonds left to uncover: " + state->notDug;
    drawString(25, 25, progression, WHITE);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    drawCells(state->cells);
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    drawImageDMA(state->cursor.x, state->cursor.y, 20, 20, shovel);
}
